# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1af3992d955f5ee07948a1cd60b15787450e979c80ad2ee6a7bec4c1335454265901590e0e98e8326e05063654afd04633634efdd4af784cbd78ee065febfb00

test:
  secret_key_base: 466ec31a53a6d740d6369a8e7b2023e9aac309c34b9f4374ee1afab00e649ba7320edfee64ea080c7751a2af319a17825f904cd4487b8852b2b06a1023902025

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
